export type Point = { x: number; y: number }
export type EnemyKind = "allocation" | "large" | "cache" | "retained" | "cycle" | "listener" | "legacy"
export type TowerKind = "gc" | "free" | "reference" | "profiler" | "cycle-detector"
export type Enemy = { id:number; kind:EnemyKind; pathIndex:number; pathProgress:number; x:number; y:number; hp:number; maxHp:number; speed:number; ramDamage:number; reward:number; radius:number; shield:number; spawnCooldown:number; dead:boolean }
export type Tower = { id:number; kind:TowerKind; x:number; y:number; level:number; cooldown:number; spent:number; powerUpgrades:number; utilityUpgrades:number }
export type Projectile = { id:number; x:number; y:number; targetId:number; damage:number; speed:number; radius:number; kind:TowerKind; dead:boolean }
export type Particle = { id:number; x:number; y:number; vx:number; vy:number; life:number; maxLife:number; size:number }
export type FloatingText = { id:number; x:number; y:number; text:string; life:number; maxLife:number }
export type WaveEntry = { kind:EnemyKind; count:number; interval:number }
export type TowerDefinition = { kind:TowerKind; name:string; shortName:string; description:string; cost:number; range:number; damage:number; fireRate:number; projectileSpeed:number }
export type GameStatus = "ready" | "wave" | "between" | "won" | "lost"
